meta_name: "PlanIt"
meta_title: "PlanIt - The best travel itinerary app"
meta_description: "Use PlanIt to visualise your travel itinerary, share it with your tripmates, and keep an eye on all your expenses."
meta_image: "home_banner.jpg"
